### ISSUE TITLE
Manifest file generated is in older version

### ISSUE THREAD

**Issue by hdavid16** [JuliaCI/PkgTemplates.jl#394] opened 2023-04-20 00:37 UTC
I get the warning:

```julia
┌ Warning: The active manifest file at `C:\...\Manifest.toml` has an old format that is being maintained.
│ To update to the new format, which is supported by Julia versions ≥ 1.6.2, run `Pkg.upgrade_manifest()` which will upgrade the format without re-resolving.
│ To then record the julia version re-resolve with `Pkg.resolve()` and if there are resolve conflicts consider `Pkg.update()`.
```

When creating a package with PkgTemplates.

**Comment by 3f6a** [comment] 2023-05-02 10:07
I am also seeing this issue, only in non-interactive mode. In case it's useful, here is the template I'm using

```

t = Template(
    ;
    host = "github.com",
    julia = v"1.8.3",

    plugins = [
        ProjectFile(; version=v"1.0.0-DEV"),
        SrcDir(),
        Tests(; project=true),
        Readme(),
        License(; name="MIT"),
        Git(; manifest=true, ssh=true),
        CompatHelper(),
        TagBot(),
        Documenter(),
        Codecov(),
        GitHubActions(; extra_versions=["1.6", "1.8"])
    ],

    interactive = false
)
```

**Comment by gdalle** [comment] 2023-07-31 21:27
Duplicate of #365

**Closed** 2023-09-02 14:02 UTC
Labels: bug
